### PR TITLE
Fix grpc closure size

### LINKED ISSUE #31: Decrease Nix closure size
Currently our closure takes about 700 MB:

```
$ storepath=$(nix-build)
$ nix-store --export $(nix-store -qR $storepath) > out-fencer
$ ls -lah out-fencer
-rw-r--r--  1 yom  staff   708M Sep 27 17:22 out-fencer
```

The biggest offenders are:

```
740 MB  └── nix
740 MB      └── store
393 MB          ├─⊕ i2nf6hslid0ak8fzgpj2m082sprihi92-clang-7.1.0
133 MB          ├─⊕ hfy6ibq1hwayv24yrh98f3avc47nmr00-llvm-7.1.0
 63 MB          ├─⊕ 0cifmxw0r6lijng796a3z3nwq67ma5b3-llvm-7.1.0-lib
 27 MB          ├─⊕ 5qk8vydayrvkq313s1srxhrnblhqvahk-grpc-1.2.0-e2cfe9d
 27 MB          ├─⊕ q959m66x0cfryybzapv7c4v0ki2jfr1a-clang-7.1.0-lib
 18 MB          ├─⊕ bhywddq18j79xr274n45byvqjb8fs52j-Libsystem-osx-10.12.6
 11 MB          ├─⊕ i7hz49am5vla34lmpkw5aqkjgd2b98hb-binutils-2.31.1
...
```

This primarily affects our Docker image size.

### PR DESCRIPTION
**Pull request by neongreen**
Fixes #31.

### CODE REVIEW

**Comment by neongreen** [comment]
```
$ nix path-info -r /nix/store/jmfccb15x6zl97mal5n1abh1jf3jyjjx-grpc-1.2.0-e2cfe9d

/nix/store/07jcv76pfgppiryv0b0nf20ygz34wvzn-swift-corefoundation
/nix/store/11sw3j3mpvyp1x0k6g35vky2crz2a9v3-curl-7.65.3
/nix/store/3j24bxhc35hwcby810ah2khihk4pl2ia-Libsystem-osx-10.12.6
/nix/store/4h3zzn9ws6b3nzww12a89vqw92mvy6px-zlib-1.2.11
/nix/store/cq3ahr8a2b9qhsr1bgxgxgkf3ybhc1w6-libc++abi-7.1.0
/nix/store/h568713mviz3q2vf94lkl1v87r0ff5vr-ICU-osx-10.10.5
/nix/store/jmfccb15x6zl97mal5n1abh1jf3jyjjx-grpc-1.2.0-e2cfe9d
/nix/store/manwblxv4n70fwji369liqc7g9jbl0vr-bash-4.4-p23
/nix/store/pbw8xa9pz5vlk7p82kzqy3lzii63gzkx-nghttp2-1.39.2-lib
/nix/store/pmsxk1p264ia2176fipaplnrvpgmic87-libc++-7.1.0
/nix/store/qjsv8zy7nhfg4g3ihz1b02hx6mn2v7iy-libssh2-1.9.0
/nix/store/qn76bbzs77dg4vba8hdpzlblg322w0n7-openssl-1.0.2t
/nix/store/r43vk5crzmnswfn4yd2vhafp3b3jx8hy-libkrb5-1.17
/nix/store/vq3xy2lpqhxl4m5vk8n5rvwv4fj7gxl1-openssl-1.1.1d
/nix/store/w2q6h9p59gz0aq7pk470kl017lvfnfbj-libxml2-2.9.9
```

Still not great – the resulting library depends on `curl` and `bash` – but much better than it was.

**Comment by neongreen** [comment]
```
$ nix why-depends /nix/store/jmfccb15x6zl97mal5n1abh1jf3jyjjx-grpc-1.2.0-e2cfe9d /nix/store/manwblxv4n70fwji369liqc7g9jbl0vr-bash-4.4-p23

/nix/store/jmfccb15x6zl97mal5n1abh1jf3jyjjx-grpc-1.2.0-e2cfe9d
╚═══bin/grpc_cpp_plugin: ….dylib.......`......./nix/store/07jcv76pfgppiryv0b0nf20ygz34wvzn-swift-corefoundation/Library/Fr…
    => /nix/store/07jcv76pfgppiryv0b0nf20ygz34wvzn-swift-corefoundation
    ╚═══Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation: ….h.................../nix/store/11sw3j3mpvyp1x0k6g35vky2crz2a9v3-curl-7.65.3/lib/libcurl.4.dylib…
        => /nix/store/11sw3j3mpvyp1x0k6g35vky2crz2a9v3-curl-7.65.3
        ╚═══lib/libcurl.4.dylib: ….p.................../nix/store/r43vk5crzmnswfn4yd2vhafp3b3jx8hy-libkrb5-1.17/lib/libgssapi_krb5…
            => /nix/store/r43vk5crzmnswfn4yd2vhafp3b3jx8hy-libkrb5-1.17
            ╚═══bin/compile_et: …#!/nix/store/manwblxv4n70fwji369liqc7g9jbl0vr-bash-4.4-p23/bin/sh.#.#.AWK=gaw…
                => /nix/store/manwblxv4n70fwji369liqc7g9jbl0vr-bash-4.4-p23
```

**Comment by layus** [comment]
Well, this is weird because all `-g` does is add debug symbols, that should precisely get stripped in the end.

**Comment by layus** [comment]
As for depending on bash through CoreFoundation, not sure if there is anything to do there.

**Review by iAmMrinal0 — APPROVED** [review]

**Pull request merged**
