### PR TITLE
Add configuration parse tests

### PR DESCRIPTION
**Pull request by neongreen**
- [x] Use `base-prelude`.
- [x] Consider using https://hackage.haskell.org/package/aeson-1.4.4.0/docs/Data-Aeson-QQ-Simple.html and write all JSON verbatim instead of constructing it out of smaller pieces.
- [x] Check that the resulting `DescriptorDefinition` looks like we expect it to look.
- [x] Avoid `Par` by writing `parseEither (parseJSON @DescriptorDefinition)` instead.
- [x] Use https://hackage.haskell.org/package/tasty-discover.

### CODE REVIEW

**Comment by mdimjasevic** [comment]
@neongreen, in the old version of the branch I used `isLeft` from `base-prelude`, but now that I reworked tests, I am not relying on the function anymore. Therefore, I can't put a check next to the first item in the check list in your PR description.

I believe I handled everything from what we discussed earlier today.

Is the GitLab CI already plugged in? I assume it is, as I see a pending CI as I'm writing this.

**Comment by neongreen** [comment]
I have rebased the branch and pushed several commits.

* `aeson-qq` and `tasty-discover` were not listed in `fencer.nix`, causing nix-build to fail.
* The `Data.Aeson.QQ` import was implicit and unqualified. I turned it into an explicit import.
* It's true that base-prelude is not necessary in the one test file that we have, but it's a good practice to use base-prelude in all modules anyway – it reduces friction when one _does_ need base-prelude. Less decisions = good.
* Similarly, the testsuite did not have a default-extension stanza. I used Cabal's "common stanzas" to ensure that all units will use the same extensions and GHC options from now on.
* I reformatted JSON as multiline. It is more readable and doesn't lead to overly long lines.
* I renamed `dd1`, `dd2`, `o` and added a section to the styleguide regarding abbreviated names.

**Comment by neongreen** [comment]
Please review / get familiar with my changes, and merge when the CI passes.

**Comment by neongreen** [comment]
Okay, the CI has passed. Given that the PR is small and the individual commits are not particularly interesting, I would recommend "Squash and merge".

**Pull request merged**
