### PR TITLE
Travis CI

### LINKED ISSUE #88: Set up Travis CI
Set up the Travis continuous integration for Fencer:

- [ ] Add a `.travis.yml` file,
- [ ] port secrets from GitLab CI settings. Variables should be encrypted and store in the `.travis.yml` file and should be only made available to jobs that actually require them,
- [ ] Consult the [Travis CI documentation](https://docs.travis-ci.com/user/languages/nix/) to see how to support Nix.

### PR DESCRIPTION
**Pull request by neongreen**
Fixes #88.

### CODE REVIEW

**Comment by neongreen** [comment]
Waiting for Travis to get activated for our repo.

**Comment by neongreen** [comment]
Need to also pass built `fencer.tar.gz` between stages.

**Comment by neongreen** [comment]
Seems to work now.

`secure:` blobs were generated by running `travis encrypt --pro GITHUB_ACCESS_TOKEN=...`.

**Comment by neongreen** [comment]
I also had to change `if: branch = master` to `if: branch = master AND type = push` because otherwise the `release_docker` job would also run on PR builds (e.g. https://travis-ci.com/juspay/fencer/jobs/255090197).

PR builds are builds for the result of merging the PR branch into `master`. They are done because the result of running CI on a branch is not necessarily the same as the result you'd get after the branch has been merged into master.

**Review by mdimjasevic — APPROVED** [review]
This looks good.

I see you used Travis CI workspaces, a feature which is currently in beta, but I guess there is no alternative in Travis CI.

**Pull request merged**
