### PR TITLE
Upgrade to a newer gRPC version

### PR DESCRIPTION
**Pull request by neongreen**

### CODE REVIEW

**Comment by neongreen** [comment]
This would also remove the IPv6 limitation.

**Comment by neongreen** [comment]
There is hope on the horizon: https://github.com/awakesecurity/gRPC-haskell/pull/98

**Review by srid — COMMENTED** [review]
Nix provides an [`overrideAttrs`](https://nixos.org/nixpkgs/manual/#sec-pkg-overrideAttrs) function if all we want to change is an attribute of the mkDerivation call:

> The function overrideAttrs allows overriding the attribute set passed to a
stdenv.mkDerivation call, producing a new derivation based on the original one.
This function is available on all derivations produced by the
stdenv.mkDerivation function, which is most packages in the nixpkgs expression
pkgs.

That allows us to directly use the upstream expression without necessarily creating a local copy for modifications. Something like this in default.nix:

```nix
    # grpc = pkgs.callPackage ./nix/grpc.nix { }; -- NOTE: not needed anymore
    grpcUpstream = with pkgs; import "${grpc-haskell-source}/nix/grpc.nix" {
      inherit stdenv fetchFromGitHub cmake zlib c-ares pkgconfig openssl protobuf gflags;
    };
    grpc = grpcUpstream.overrideAttrs (oldAttrs: rec {
      # we want to make sure the result does not drag
      # the C compiler into the closure
      disallowedReferences = with pkgs; [ stdenv.cc ];
    });
```

The same can be done for ./nix/protobuf.nix given that it seems to modify only a couple of attributes to its mkDerivation.

Or, am I missing some other context for keeping a local copy of these files?

**Comment by neongreen** [comment]
Thanks! I didn't know about `overrideAttrs`.

**Review by srid — APPROVED** [review]

**Pull request merged**
