### PR TITLE
Use Cachix

### PR DESCRIPTION
**Pull request by neongreen**

### CODE REVIEW

**Comment by neongreen** [comment]
* CI time, before: 22 minutes.
* CI time, after: 5 minutes.

**Review by mdimjasevic — APPROVED** [review]
While this is good, I'm not so knowledgeable of Nix so can you explain how does Cachix in this case differ from the official repository at https://cache.nixos.org?

**Comment by neongreen** [comment]
We can't push our own builds to cache.nixos.org – it only hosts nixpkgs builds. So we end up rebuilding dependencies like `grpc` over and over.

**Comment by neongreen** [comment]
Geez, I just wasted some time trying to understand why `grpc` got rebuilt instead of fetched from cache, and only then realized that the "build docker image" commit also patches `grpc` :/

For further reference, here's the investigation log.

---

Find the hashes of `grpc-1.2.0-e2cfe9d.drv` in CI logs.

Download the hashes:

```
nix-store -r /nix/store/039qhixqjck93f811sd0kx9vhlx6jmvn-grpc-1.2.0-e2cfe9d.drv 
nix-store -r /nix/store/k39hksznpdd9siv8db1xvzi00lwb6vs1-grpc-1.2.0-e2cfe9d.drv
```

Install [nix-diff](https://hackage.haskell.org/package/nix-diff):

```
cabal v2-install nix-diff
```

Diff the derivations:

```
nix-diff \
  /nix/store/039qhixqjck93f811sd0kx9vhlx6jmvn-grpc-1.2.0-e2cfe9d.drv \
  /nix/store/k39hksznpdd9siv8db1xvzi00lwb6vs1-grpc-1.2.0-e2cfe9d.drv
```

```diff
- /nix/store/039qhixqjck93f811sd0kx9vhlx6jmvn-grpc-1.2.0-e2cfe9d.drv:{out}
+ /nix/store/k39hksznpdd9siv8db1xvzi00lwb6vs1-grpc-1.2.0-e2cfe9d.drv:{out}
• The set of input sources do not match:
    + /nix/store/frdp9x4pfl8b82ny84mbhnzg1dyv8mm4-grpc-ipv4.patch
```

**Pull request merged**
